import java.util.ArrayList;

public class BranchManager extends Employee 
{   
	//Counter to increment autogenerated ID


	public BranchManager(String ID,String password , String name, String type, double salary, double hourlyRate)
	{
		super(ID, password, name, type, salary, hourlyRate);
	}
	
	
	public void assignSaleEmployee(SalesConsultant salesConsultant, Sale property, String salesConsultantID) throws EmployeeAlreadyAssignedProperty, IncorrectEmployeeID
	{
		if (!salesConsultant.getID().equalsIgnoreCase(salesConsultantID))
		{
			throw new IncorrectEmployeeID("Incorrect Employee ID");
		}
		else if(salesConsultant.getProperty() == null)
		{
			property.setSalesConsultant(salesConsultantID);
			salesConsultant.setProperty(property.getPropertyID());
			System.out.println("Successfully assigned property with id "+property.getPropertyID()+" to "+salesConsultant.getID());
		}
		else if(salesConsultant.getProperty() != null)
		{
			throw new EmployeeAlreadyAssignedProperty("The sales consultant "+salesConsultant.getID()+" is already assigned a property");
		}
		
	}
	
	public void assignRentalEmployee(PropertyManager propertyManager, Rental property, String propertyManagerID) throws EmployeeAlreadyAssignedProperty, IncorrectEmployeeID
	{
		
		if(!propertyManager.getID().equalsIgnoreCase(propertyManagerID))
		{
			throw new IncorrectEmployeeID("Incorrect Employee ID");
		}
		else if (propertyManager.getProperty() != null)
		{
			throw new EmployeeAlreadyAssignedProperty("The property manager "+propertyManager.getID()+" is already assigned a property");
		}
		else if(propertyManager.getProperty() == null)
		{
			property.setPropertyManager(propertyManagerID);
			propertyManager.setProperty(property.getPropertyID());
			System.out.println("Successfully assigned property with id "+property.getPropertyID()+" to "+propertyManager.getID());
		}
			
	}
	
	public boolean approveHours(double hours) throws HourException
	{
		if(hours < 0)
		{
			throw new HourException("Please enter a positive value for hours");
		}
		else if(hours <= 40)
		{
			return true;
		}
		else
		{
			return false;
		}
	}



	
	
}
