
public class BranchManager extends Employee 
{          //Counter to increment autogenerated ID
	
	public BranchManager(String ID,String password , String name, String type, double salary, double hourlyRate)
	{
		super(ID, password, name, type, salary, hourlyRate);
	}
	
	
	public void assignSaleEmployee(SalesConsultant salesConsultant, Sale property, String salesConsultantID)
	{
		if(salesConsultant.getProperty() == null)
		{
			property.setSalesConsultant(salesConsultantID);
			salesConsultant.setProperty(property.getPropertyID());
			System.out.println("Successfully assigned property with id "+property.getPropertyID()+" to "+salesConsultant.getID());
		}
		else if(salesConsultant.getProperty() != null)
		{
			System.out.println("The sales consultant "+salesConsultant.getID()+" is already assigned a property");
		}
		else
		{
			System.out.println("Cannot assign property "+property.getPropertyID()+" to "+salesConsultant.getID());
		}
			
	}
	
	public void assignRentalEmployee(PropertyManager propertyManager, Rental property, String propertyManagerID)
	{
		if(propertyManager.getProperty() == null)
		{
			property.setPropertyManager(propertyManagerID);
			propertyManager.setProperty(property.getPropertyID());
			System.out.println("Successfully assigned property with id "+property.getPropertyID()+" to "+propertyManager.getID());
		}
		else if (propertyManager.getProperty() != null)
		{
			System.out.println("The property manager "+propertyManager.getID()+" is already assigned a property");
		}
		else
		{
			System.out.println("Cannot assign property "+property.getPropertyID()+" to "+propertyManager.getID());
		}
			
	}
	
	public boolean approveHours(double hours) throws HourException
	{
		if(hours < 0)
		{
			throw new HourException("Please enter a positive value for hours");
		}
		else if(hours <= 40)
		{
			return true;
		}
		else
		{
			return false;
		}
	}
}
