
public class BranchManager extends Employee 
{
	private static int bmCounter = 0;          //Counter to increment autogenerated ID
	
	
	public BranchManager(String name, String type, double salary, double hourlyRate)
	{
		super(name, type, salary, hourlyRate);
	}
	
	public String setID()
	{
		return " ";
	}
	
	public Employee assignEmployee()
	{
		Employee e = null;
		return e;
	}
	
	public boolean approveHours(double hours) throws HourException
	{
		if(hours < 0)
		{
			throw new HourException("Incorrect hours entered");
		}
		else if(hours <= 20)
		{
			return true;
		}
		else
		{
			return false;
		}
	}
}
