
public class BranchManager extends Employee 
{
	private static int bmCounter = 0;          //Counter to increment autogenerated ID
	
	
	public BranchManager(String name, String type, double salary)
	{
		super(name, type, salary);
	}
	
	public String setID()
	{
		return " ";
	}
	
	public Employee assignEmployee()
	{
		Employee e = null;
		return e;
	}
	
	public boolean approveSalary()
	{
		return true;
	}
}
